### ISSUE TITLE
Simplified Chinese Translation in wrong place.

### ISSUE THREAD

**Issue by MarbleGateKeeper** [InJir69/create_brass_coated#3]
See https://github.com/InJir69/create_brass_coated/commit/9a5a35b432f760d82b94942d3e31361948776cff

It should be put into `src/main/resources/assets/create_brass_coated/lang/`。

**Comment by InJir69** [comment]
I will fix that when I will get access to my computer

**Comment by InJir69** [comment]
Translation is working while in this folder

**Comment by InJir69** [comment]
in src/generated/resources/assets/create_brass_coated/lang/ it also works
